// Generated by CoffeeScript 1.6.3
var io, ten;

io = require("socket.io").listen(3060);

io.sockets.on("connection", function(s) {
  s.emit("helloWorld");
  s.emit("hello", {
    "what": "is this"
  });
  setInterval(function() {
    return ten(s);
  }, 5000);
  s.on("return", function(data) {
    return console.log(data);
  });
  return s.on("whatfuckthe", function(data) {
    return console.log(data);
  });
});

ten = function(socket) {
  return socket.emit("fiveSecond");
};
