// Generated by CoffeeScript 1.6.3
var io, ten;

io = require("socket.io").listen(3060);

io.sockets.on("connection", function(s) {
  s.emit("helloWorld");
  s.emit("hello", {
    "what": "is this"
  });
  return setInterval(function() {
    return ten(s);
  }, 5000);
});

ten = function(socket) {
  return socket.emit("fiveSecond");
};
